import 'dart:io';

import 'package:atef_physics/core/constants/firebase_strings.dart';
import 'package:atef_physics/core/network/api_error_handler.dart';
import 'package:atef_physics/core/network/api_result.dart';
import 'package:atef_physics/features/header/model/header_model.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_storage/firebase_storage.dart';

class HeaderApiServices {
  /// Adds a header to Firestore.
  Future<ApiResult<void>> addHeader(String path, bool isVideo) async {
    try {
      String videoPath = path;

      if (!isVideo) {
        final coursePhotoRef = FirebaseStorage.instance.ref(
          '${FirebaseStrings.header}/${DateTime.now().millisecondsSinceEpoch}',
        );
        final file = await coursePhotoRef.putFile(File(path));
        videoPath = await file.ref.getDownloadURL();
      }

      final header = HeaderModel(
        id: '', // ID will be autogenerated in Firestore
        videoPath: videoPath,
        isVideo: isVideo,
      );

      await FirebaseFirestore.instance
          .collection(FirebaseStrings.header)
          .doc()
          .set(header.toJson());

      return const ApiResult.success(null);
    } catch (e) {
      return ApiResult.failure(
        ApiErrorHandler(
          statusCode: 00,
          statusMessage: e.toString(),
          success: false,
        ),
      );
    }
  }

  /// Fetches all headers from Firestore.
  Future<ApiResult<List<HeaderModel>>> getHeaders() async {
    try {
      final querySnapshot = await FirebaseFirestore.instance
          .collection(FirebaseStrings.header)
          .get();

      final headers = querySnapshot.docs.map((doc) {
        return HeaderModel(
            id: doc.id,
            videoPath: doc.data()[FirebaseStrings.path],
            isVideo: doc.data()[FirebaseStrings.isVideo]);
      }).toList();

      return ApiResult.success(headers);
    } catch (e) {
      return ApiResult.failure(
        ApiErrorHandler(
          statusCode: 00,
          statusMessage: e.toString(),
          success: false,
        ),
      );
    }
  }

  /// Removes a header from Firestore and deletes its associated file from Firebase Storage if necessary.
  Future<ApiResult<void>> removeHeader(HeaderModel header) async {
    try {
      // If it's not a video, delete the file from Firebase Storage
      if (!header.isVideo) {
        final fileRef = FirebaseStorage.instance.refFromURL(header.videoPath);
        await fileRef.delete();
      }

      // Delete the document from Firestore
      await FirebaseFirestore.instance
          .collection(FirebaseStrings.header)
          .doc(header.id)
          .delete();

      return const ApiResult.success(null);
    } catch (e) {
      return ApiResult.failure(
        ApiErrorHandler(
          statusCode: 00,
          statusMessage: e.toString(),
          success: false,
        ),
      );
    }
  }
}
